name: Select Winner

on:
  workflow_dispatch:  # Triggered manually

jobs:
  select_winner:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Python script
        run: python notus_guild_winner_selection.py

      - name: Read winner from file
        id: winner
        run: echo "::set-output name=winner::$(cat winner.txt)"

      - name: Print winner
        run: echo "Winner:${{ steps.winner.outputs.winner }}"
