name: Select Winner

on:
  workflow_dispatch:
    inputs:
      draw_name:
        description: 'Name of the draw'
        required: true

jobs:
  select_winner:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Python script
        run: python winner_selection.py

      - name: Read winner from file
        id: winner
        run: echo "WINNER=$(cat winner.txt)" >> $GITHUB_ENV

      - name: Print winner
        run: echo "Winner: ${{ steps.winner.outputs.winner }}"
