name: Select Winner

on:
  workflow_dispatch:
    inputs:
      draw_name:
        description: 'Name of the draw'
        required: true

jobs:
  select_winner:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Python script
        run: python notus_guild_winner_selection.py

      - name: Read winner from file and set as environment variable
        run: |
          winner=$(cat winner.txt)
          echo "WINNER=${winner}" >> $GITHUB_ENV
          echo "DRAW_NAME=${{ github.event.inputs.draw_name }}" >> $GITHUB_ENV

      - name: Print winner and draw name
        run: echo "Winner:${{ env.WINNER }} | Draw Name:${{ env.DRAW_NAME }}"
